### ISSUE TITLE
OPTIONS

### ISSUE THREAD

**Issue by radeklos** [thisissoon/API-Specification#4]
I've just realised that our API spec doesn't have anything about `OPTIONS` method. The method can be used as an api descriptor which returns a valid data structure which is accepted by an endpoint. 

```
OPTIONS /bla
```

Will return:

``` json
{
  "POST": {
    "description": "blabla",
    "parameters": {
      "title": {
        "type": "string",
        "description": "bla bla bla.",
        "required": true
      }
}
```

@krak3n @edwardoparearyee @peeklondon @jamesjwarren any thoughts?

**Comment by krak3n** [comment]
Good spot! Not sure about it returning all that data though, could be hard to maintain that.

**Comment by radeklos** [comment]
True.. But we can take how can we extract metadata from serialisers..

**Comment by krak3n** [comment]
Yeah, I'm just worried about other language stacks say we did something in Rust where it maybe harder to do this stuff. Maybe it should be a best effort basis rather than a full on hard a fast rule?

At a minimum OPTIONS tells you what methods are supported, above that is a bonus?
